Added page settings and snackbar
wearethefuture-org/shop-admin pull request #10
Opened 2021-02-01 08:20 UTC by prystoinyi

2021-02-01 15:07 UTC, ArtemBozhok requested changes

2021-02-01 15:07 UTC, ArtemBozhok commented on src/store/sagas/settings.saga.ts
> +    console.log(error);
якщо вже почав робити обробку помилок, то закінчуй)
Давай тут теж ти удеш записувати меседж і показувати снекбар, якщо даги зафетчитит не вдалось.
+ в компонентах які юзають ці дани постав перевірку, що якщо нічого не прийшло, то те ж потрібно про це сказати.

2021-02-01 15:07 UTC, ArtemBozhok commented on src/store/store.ts
> +   composeWithDevTools()
нехай покищо буде закоментовано, це окрема таска.
Потрібно запушити логер тільки в дев режимі.

2021-02-01 15:07 UTC, ArtemBozhok commented on src/store/store.ts
> +saga.run(sagaSettingsWatcher);
тут уже нам потрібно міняти підхід. А якщо буде 20 сагаранів? Потрібно переробити на массив, якщо не розберешься то залишай на потім.

2021-02-01 16:23 UTC, prystoinyi commented on src/components/Common/SnackBar.tsx
> +}));
Коли імпортую scss то компонент матеріал бере свої стилі, перевизначає мої

2021-02-01 17:29 UTC, prystoinyi commented on src/components/Content/Settings/SettingsContent.tsx
> +                <span className={classes.dateTitle}>Оновлено</span>{" "}
Це пробел так переробив претір, дата на 69 строчці

2021-02-02 16:15 UTC, ArtemBozhok requested changes

2021-02-02 16:15 UTC, ArtemBozhok commented on src/hooks/useSnackbar.ts
> +  const errorMessage = useSelector((state: RootState) => state.snackBar.errorMessage);
давай ти витягнеш просто стейт снекбара, а потім поверниш всі необхідни об'єкти. Навіщо юзати хук 3 рази, якщо можна 1.

2021-02-02 18:44 UTC, merged