Slider
wearethefuture-org/shop-admin pull request #12
Opened 2021-02-08 17:09 UTC by coldmorning4

2021-02-16 13:34 UTC, ArtemBozhok requested changes

2021-02-16 13:34 UTC, ArtemBozhok commented on src/components/Forms/Slider-form/Slider-form.tsx
> +      console.log(values.image)
консоль логи не пушимо в гіт

2021-02-16 13:34 UTC, ArtemBozhok commented on src/components/Forms/Slider-form/Slider-form.tsx
> +        props.dispatch(fetchAddSliders(values.id, values.name, values.text, values.image, values.href, values.isShown, values.priority));
...values

2021-02-16 13:34 UTC, ArtemBozhok commented on src/components/Tables/Sliders/Body/Table-body.tsx
> +  const {data, dispatch} = useSliders();
не правильна логіка. Звичайний функціональний компонент не повинен юзати якісь хуки і стукати на сервак. Ти вже заюзала цей хук на верхньому рівні в slider-container, прокидуй усі данні звідти куди тобі потрібно.

Так аплікуху зручно тестувати і одразу зрозумілий потік данних, де вони прийши і куди пішли.

2021-02-16 13:34 UTC, ArtemBozhok commented on src/store/sagas/sliders.saga.ts
> +        if (newSlider.status === 200) {
ця перевірка не потрібно, ти спеціально щоб відловити помилку обернула в трайк кетч. все що не 200 буде передеано в ерор

2021-02-16 13:34 UTC, ArtemBozhok commented on src/store/sagas/services/slider.service.ts
> +    const somw_shit =  await api.sliders.delete(data);
я правильно зрозумів що це some_shit?

2021-02-16 13:34 UTC, ArtemBozhok commented on src/api/api.ts
> +      return axios.patch(`${root}/slider/${slider.id}`, slider)
це щось не то взгаалі.
Тут повинен бути описані прості запити без всяких форм дата і т.д.

запит повинен мати вигляд такий як і на додавання категорії, напкриклад add: (slide) => axios.post(`${root}/slide`, slide), 
де твій slide - це об'єкт у якому містяться усі необхідні дані для запиту заздалегіть підготовлені. У формі формується цей обєкт і просто передається сюди в цей метод.

Крім того, у тебе куча коду, що повторюється. Винеси його в корему функцію і юзай у формах де потрібно, щоб сформувати підходящий об'єкт.

2021-02-23 12:41 UTC, ISvirko commented on src/store/sagas/sliders.saga.ts
> +        console.log(error);
на помилки можна додати снекбар з помилкою
catch (error) {
  yield put(failSnackBar(error.message));
}

2021-02-23 12:42 UTC, ISvirko commented on src/store/sagas/sliders.saga.ts
> +        yield put(updateSlider(newSlider));
так само при успішній операції можна показати зелененький снекбар
yield put(successSnackBar());

2021-02-23 13:19 UTC, ISvirko commented on src/components/Containers/Sliders-container.tsx
> +import SlidersTable from '../Tables/Sliders/Sliders-table';
бажано б замінити усюди  sliders на slides, бо не дуже зрозуміло, що слайдер один, а слайдів багато

2021-02-23 13:21 UTC, ISvirko commented on src/components/Forms/Slider-form/Inner-form.tsx
> +      />
можна стилізувати інпут так, щоб було видно, що там є дропзона

2021-02-23 13:23 UTC, ISvirko commented on src/components/Tables/Sliders/Body/Table-body.tsx
> +              <Button variant="contained" color="primary" onClick={() => handleClickDelete(row)}>
на кнопку delete можна color='secondary'

2021-02-23 13:24 UTC, ISvirko commented on src/components/Tables/Sliders/Body/Table-body.tsx
> +            <TableCell component="th" scope="row">{row.id}</TableCell>
широка колонка id, може б вужче зробити

2021-02-23 13:25 UTC, ISvirko commented on src/components/Modals/Slider-modal-edit.tsx
> +        <DialogTitle id="form-dialog-title"></DialogTitle>
додай заголовок, щоб не було пустого поля

2021-02-23 13:26 UTC, ISvirko commented on src/components/Forms/Slider-form/Inner-form.tsx
> +          color="primary"
теж можна color="secondary"

2021-02-23 13:28 UTC, ISvirko commented on src/components/Containers/Sliders-container.tsx
> +      <FormDialog
зараз кнопка 'додати' під таблицею, це незручно. треба підняти її наверх

2021-02-23 13:29 UTC, ISvirko commented on src/components/Tables/Sliders/Sliders-table.tsx
> +      <CircularProgress/>
лоадер має бути тільки на loading, зараз коли немає даних він крутиться

2021-03-02 12:23 UTC, ArtemBozhok approved these changes

2021-03-02 12:23 UTC, merged