Add order page 83
wearethefuture-org/shop-admin pull request #27
Opened 2021-04-22 18:59 UTC by mozzie2004

2021-04-23 16:49 UTC, mozzie2004 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страницу ордеров для админки](https://trello.com/c/fiuwt7vz/83-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D0%BE%D1%80%D0%B4%D0%B5%D1%80%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%BA%D0%B8)

2021-05-05 14:14 UTC, ArtemBozhok requested changes

2021-05-05 14:14 UTC, ArtemBozhok commented on src/components/AppDataTable/AppDataTable.tsx
> +  title: any;
було правильно, ніякий це не any

2021-05-05 14:14 UTC, ArtemBozhok commented on src/components/Router/Router.tsx
> +
видалити

2021-05-05 14:14 UTC, ArtemBozhok commented on src/components/Router/Router.tsx
> +
видалити і налаштувати преттір, щоб такого не було

2021-05-05 14:14 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersEditQuantity.tsx
> +          }
створити хендлер для setEditable і в ному зробити цю перевірку.  В онклік передавати хенделр,

2021-05-05 14:14 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersEditQuantity.tsx
> +        <DoneIcon color="primary" onClick={(e) => onQuantityChanged(e, orderId, row.product.id)} />
також стоврити хендлер

2021-05-05 14:14 UTC, ArtemBozhok commented on src/interfaces/IOrders.ts
> +  currentOrder: IGetOrders | any;
не може це бути any

2021-05-05 14:14 UTC, ArtemBozhok commented on src/interfaces/IOrders.ts
> +  user: object;
це не object

2021-05-05 14:14 UTC, ArtemBozhok commented on src/store/reducers/orders.reducer.ts
> +          ...state.list.slice(idx + 1),
юзай map як на 121 строчці

2021-05-05 14:14 UTC, ArtemBozhok commented on src/store/sagas/orders.saga.ts
> +export function* updateOrderStatusWorker({ data: { id, status } }: IActions): SagaIterator<void> {
войд для чого тут?

2021-05-05 14:15 UTC, ArtemBozhok requested changes

2021-05-05 14:15 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersEditStatus.tsx
> +    OPEN = 'open',
open видяляємо

2021-05-05 14:23 UTC, mozzie2004 commented on src/components/AppDataTable/AppDataTable.tsx
> +  title: any;
там просто в документації писало, що можна компонент передавати. я в title вивів email, телефон... Переробляти там шапку якось по другому, чи можна якийсь тип замість стрінг поставити?

2021-06-01 10:30 UTC, ArtemBozhok requested changes
Виправити минулі коменти + нові

2021-06-01 10:30 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersEditStatus.tsx
> +
винести в папку бо це потрібно юзати в інших місцях

2021-06-01 10:30 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersTable.tsx
> +const OrdersTable = ({ list, activeColumns }) => {
нема типізації

2021-06-01 10:30 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersTable.tsx
> +    console.log('pafge');
видаляй усі консоль логи

2021-06-01 10:30 UTC, ArtemBozhok commented on src/components/Tables/Users/UsersTable.tsx
> +// import UsersRoleEdit from './UsersEditRole';
видаляй усе що не потрібно, не коментуй

2021-06-01 10:30 UTC, ArtemBozhok commented on src/components/Tables/Orders/OrdersItemTableHeader.tsx
> +const OrdersItemTableHeader = ({ order }) => {
все типізувати

2021-06-15 12:22 UTC, ArtemBozhok approved these changes

2021-06-15 12:22 UTC, merged