Task 145
wearethefuture-org/shop-admin pull request #35
Opened 2021-06-25 08:25 UTC by pinokio221

2021-06-25 08:27 UTC, pinokio221 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Фікс переходу по слайдеру](https://trello.com/c/MBT100Mp/145-%D1%84%D1%96%D0%BA%D1%81-%D0%BF%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D1%83-%D0%BF%D0%BE-%D1%81%D0%BB%D0%B0%D0%B9%D0%B4%D0%B5%D1%80%D1%83)

2021-06-25 12:19 UTC, ArtemBozhok requested changes

2021-06-25 12:19 UTC, ArtemBozhok commented on .env.example
> +REACT_APP_PROD_DOMAIN=http://localhost:4000
Ці зміни ніяк не стосуються задачі.
Залиш все як було. На проді прописані конфіги під такую логіку і міняти її немає потреби.

2021-06-25 12:19 UTC, ArtemBozhok commented on src/api/config.ts
> +export default clientUrl;
видаляй

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +
лишній відступ

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +      if(currentLink.trim() != '') {
налаштуй prettier немає пробілів

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +      if(currentLink.trim() != '') {
не бачу, щоб ти десь юзав змінну timeout

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +      if(currentLink.trim() != '') {
Потрібно використовувати завжди строгий режим порівняння !===

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +        }
позбудься конструкцій елс іф, такий код погано читається

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +      }
в тебе ніде немає пустого переноса рядка навіть якщо це якийсь інший смисловий блок коду

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +
один відутсп лишній

2021-06-25 12:19 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +          }}
налаштуй преттір і такого не буде.

2021-06-30 12:12 UTC, ArtemBozhok approved these changes

2021-06-30 12:25 UTC, ArtemBozhok commented
https://buy-all.store/zhinochii-odiah/litni-sukni/elegantnoe-plate-razrezom
https://buy.com/zhinochii-odiah/litni-sukni/elegantnoe-plate-razrezom
ця лінка не замінюється на відносну, функція підміни не розуміє де домен.

2021-06-30 12:27 UTC, ArtemBozhok requested changes

2021-06-30 12:27 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +  const validateSliderLink = (e: any) => {
це не eny а React event

2021-06-30 12:27 UTC, ArtemBozhok commented on src/components/Forms/Slide-form/Inner-form.tsx
> +        if (currentLink.includes('http://') && currentLink.length > 7) {
юзай регулярки для перевірки домена. 
Функція не універсальна

2021-07-02 12:52 UTC, ArtemBozhok approved these changes

2021-07-02 12:53 UTC, merged